### ISSUE TITLE
User Accounts

### ISSUE THREAD

**Issue by NirmalAgnihotri** [TritonSE/LAK-Goods-Transport-Application#20]
**Describe the feature to implement.**
Implement accounts with JWT+ Passport + Bcrypt. Here are some resources from the feature doc regarding this method of authentication. The TSE project Octavian is the best example and resource for this.
Salting and hashing passwords with bcrypt: https://heynode.com/blog/2020-04/salt-and-hash-passwords-bcrypt/
Authentication and authorization with JWT: https://www.section.io/engineering-education/how-to-build-authentication-api-with-jwt-token-in-nodejs/

**Figma Screenshot if applicable**

**Additional context if applicable**

**Comment by aworld1** [comment]
Accounts implemented with Firebase through phone number to email conversion.
