### ISSUE TITLE
Make Changes to Job API

### ISSUE THREAD

**Issue by NirmalAgnihotri** [TritonSE/LAK-Goods-Transport-Application#27]
**Describe the feature to implement.**
Make the changes to the Jobs and User Schemas and Jobs API we discussed in the meeting to support a user being a driver and client. The user now has 4 additional lists to track owned and applied jobs and whether they are completed or not. The jobs schema has a status variable and an assignedDriver field. 
Changes are described further in this doc https://docs.google.com/document/d/11TT4MpG4iZxDf0QfK33fsEUGnp8jhYH4Y0ZJOqaKbN4/edit#.
**Figma Screenshot if applicable**

**Additional context if applicable**

**Comment by AmanKAggarwal** [comment]
Job API Routes descriptions:
https://docs.google.com/spreadsheets/d/1h2y0m6q81K6nrAfRYWMsMq0XUOJNiPEx2Sr4_kw0uUY/edit#gid=0

**Comment by AmanKAggarwal** [comment]
Also, add documentation for backend error handling
