### ISSUE TITLE
Password Reset Second Part

### ISSUE THREAD

**Issue by NirmalAgnihotri** [TritonSE/LAK-Goods-Transport-Application#30]
**Describe the feature to implement.**
Validate the OTP and actually change the Pin based on what the client provides. These might need to be split up into 2 separate methods since on the frontend we are only allowing the user to provide a new pin if the OTP they provided was valid in the first place. If you feel that validating the OTP should be part of the other task, drop a message in our slack group chat with Aammya and I.
**Figma Screenshot if applicable**
![image](https://user-images.githubusercontent.com/53363382/160526673-a8c2bca8-290c-4002-8e17-c24b2dd5c167.png)

**Additional context if applicable**

**Comment by aworld1** [comment]
This is done as an implementation of two methods, pushed on my feature branch.
