### ISSUE TITLE
Password Reset OTP Part

### ISSUE THREAD

**Issue by NirmalAgnihotri** [TritonSE/LAK-Goods-Transport-Application#31]
**Describe the feature to implement.**
The user will provide an OTP before they are allowed to reset their password. Write a function to send an OTP to the user through text and then receive that OTP. So it is essentially the first 3 steps of the Pin Reset flow in the screenshot below. Ask in the group chat with Assaf and I if you have any questions.
**Figma Screenshot if applicable**
![image](https://user-images.githubusercontent.com/53363382/160525817-5fb65e33-37e8-4f2a-8caf-5c624d59e631.png)

**Additional context if applicable**

**Comment by aworld1** [comment]
This is done and potentially working, just unable to test without UI due to Firebase restrictions.
