### ISSUE TITLE
Job Context API Implementation

### ISSUE THREAD

**Issue by NirmalAgnihotri** [TritonSE/LAK-Goods-Transport-Application#34]
**Describe the feature to implement.**
We want to save on requests by only getting job data once in a top level component and making that data part of a context that all of the components in the accepting applicant flow can share. Keep in mind that the data is grabbed whenever a job thumbnail is clicked.
**Figma Screenshot if applicable**

**Additional context if applicable**
Official Context documentation can be found [here](https://reactjs.org/docs/context.html). This is also a good [blog](https://blog.devgenius.io/react-native-state-management-with-context-api-61f63f5b099) for using context with React Native

**Comment by AmanKAggarwal** [comment]
Talked during meeting - Context does not seem to be needed here so will move on without context
